[package]
name = "sanitizer"
version = "0.1.0"
authors = ["Tyler Hallada <tyler@consider.co>"]
edition = "2018"

[dependencies]
html5ever = "*"
lazy_static = "1.3.0"
maplit = "1.0.1"
string_cache = "0.7"
typed-arena = "1.4.1"
url = "1.7.2"
