[package]
name = "sanitizer"
version = "0.1.0"
authors = ["Tyler Hallada <tyler@consider.co>"]
edition = "2018"

[dependencies]
cssparser = "0.27.2"
html5ever = "*"
lazy_static = "1.4.0"
maplit = "1.0.2"
string_cache = "0.8"
typed-arena = "2.0.1"
url = "2.1.1"
